export interface SheetData {
  id: string
  name: string
  type: 'project' | 'tasks' | 'reports' | 'blank'
  columns: string[]
  data: Record<string, any>[]
}

export const SHEET_TEMPLATES: Record<string, SheetData> = {
  'project-database': {
    id: 'project-database',
    name: 'Project Database',
    type: 'project',
    columns: ['Project Name', 'Status', 'Priority', 'Assignee', 'Due Date', 'Progress', 'Category'],
    data: [
      {
        id: 1,
        'Project Name': 'Website Redesign',
        'Status': 'In Progress',
        'Priority': 'High',
        'Assignee': 'Sarah Chen',
        'Due Date': '2024-02-15',
        'Progress': 75,
        'Category': 'Design'
      },
      {
        id: 2,
        'Project Name': 'Mobile App Development',
        'Status': 'Planning',
        'Priority': 'Medium',
        'Assignee': 'Mike Johnson',
        'Due Date': '2024-03-01',
        'Progress': 25,
        'Category': 'Development'
      },
      {
        id: 3,
        'Project Name': 'Database Migration',
        'Status': 'Completed',
        'Priority': 'High',
        'Assignee': 'Alex Rodriguez',
        'Due Date': '2024-01-30',
        'Progress': 100,
        'Category': 'Infrastructure'
      },
      {
        id: 4,
        'Project Name': 'User Research Study',
        'Status': 'In Progress',
        'Priority': 'Medium',
        'Assignee': 'Emma Wilson',
        'Due Date': '2024-02-20',
        'Progress': 60,
        'Category': 'Research'
      }
    ]
  },
  'team-tasks': {
    id: 'team-tasks',
    name: 'Team Tasks',
    type: 'tasks',
    columns: ['Task', 'Assigned To', 'Status', 'Priority', 'Due Date', 'Department', 'Estimated Hours'],
    data: [
      {
        id: 1,
        'Task': 'Code Review - Authentication Module',
        'Assigned To': 'David Kim',
        'Status': 'In Progress',
        'Priority': 'High',
        'Due Date': '2024-02-10',
        'Department': 'Engineering',
        'Estimated Hours': 4
      },
      {
        id: 2,
        'Task': 'Design System Documentation',
        'Assigned To': 'Lisa Park',
        'Status': 'Pending',
        'Priority': 'Medium',
        'Due Date': '2024-02-12',
        'Department': 'Design',
        'Estimated Hours': 8
      },
      {
        id: 3,
        'Task': 'Customer Feedback Analysis',
        'Assigned To': 'John Smith',
        'Status': 'Completed',
        'Priority': 'Low',
        'Due Date': '2024-02-05',
        'Department': 'Product',
        'Estimated Hours': 6
      },
      {
        id: 4,
        'Task': 'Security Audit Preparation',
        'Assigned To': 'Maria Garcia',
        'Status': 'In Progress',
        'Priority': 'High',
        'Due Date': '2024-02-08',
        'Department': 'Security',
        'Estimated Hours': 12
      },
      {
        id: 5,
        'Task': 'Performance Testing',
        'Assigned To': 'Tom Brown',
        'Status': 'Pending',
        'Priority': 'Medium',
        'Due Date': '2024-02-15',
        'Department': 'QA',
        'Estimated Hours': 10
      }
    ]
  },
  'reports': {
    id: 'reports',
    name: 'Reports',
    type: 'reports',
    columns: ['Report Name', 'Type', 'Generated By', 'Date Created', 'Status', 'Recipients', 'File Size'],
    data: [
      {
        id: 1,
        'Report Name': 'Monthly Performance Report',
        'Type': 'Performance',
        'Generated By': 'Analytics System',
        'Date Created': '2024-02-01',
        'Status': 'Published',
        'Recipients': 'Management Team',
        'File Size': '2.4 MB'
      },
      {
        id: 2,
        'Report Name': 'User Engagement Analytics',
        'Type': 'Analytics',
        'Generated By': 'Sarah Chen',
        'Date Created': '2024-02-03',
        'Status': 'Draft',
        'Recipients': 'Product Team',
        'File Size': '1.8 MB'
      },
      {
        id: 3,
        'Report Name': 'Security Compliance Audit',
        'Type': 'Security',
        'Generated By': 'Maria Garcia',
        'Date Created': '2024-01-28',
        'Status': 'Published',
        'Recipients': 'Executive Team',
        'File Size': '3.2 MB'
      },
      {
        id: 4,
        'Report Name': 'Financial Summary Q1',
        'Type': 'Financial',
        'Generated By': 'Finance Department',
        'Date Created': '2024-01-31',
        'Status': 'Published',
        'Recipients': 'All Departments',
        'File Size': '1.1 MB'
      }
    ]
  }
}

export const BLANK_SHEET_TEMPLATE: SheetData = {
  id: 'blank',
  name: 'New Sheet',
  type: 'blank',
  columns: ['Column 1', 'Column 2', 'Column 3'],
  data: []
}

// Blank Template with Project Management Hub styling
export const BLANK_TEMPLATE: SheetData = {
  id: 'blank-template',
  name: 'Blank Template',
  type: 'blank',
  columns: ['Name', 'Status', 'Priority', 'Date Created', 'Category', 'Notes'],
  data: [
    {
      id: 1,
      'Name': 'Sample Item 1',
      'Status': 'Active',
      'Priority': 'High',
      'Date Created': '2024-01-15',
      'Category': 'General',
      'Notes': 'This is a sample entry. You can import CSV/Excel files or add your own data.'
    },
    {
      id: 2,
      'Name': 'Sample Item 2',
      'Status': 'Pending',
      'Priority': 'Medium',
      'Date Created': '2024-01-16',
      'Category': 'General',
      'Notes': 'Perfect for importing data or starting from scratch with PMH styling.'
    }
  ]
}

export function getSheetDataById(sheetId: string): SheetData {
  // Map common sheet names to template IDs
  const nameToId: Record<string, string> = {
    'Project Database': 'project-database',
    'Team Tasks': 'team-tasks',
    'Reports': 'reports',
    'Blank Template': 'blank-template'
  }
  
  const templateId = nameToId[sheetId] || sheetId.toLowerCase().replace(/\s+/g, '-')
  
  if (templateId === 'blank-template') {
    return BLANK_TEMPLATE
  }
  
  return SHEET_TEMPLATES[templateId] || { ...BLANK_SHEET_TEMPLATE, id: sheetId, name: sheetId }
}
